server:
  port: 8888

# Spring Boot Admin Serveré…ç½®
spring:
  boot:
    admin:
      monitor:
        status-lifetime: 100000
      ui:
        external-views:
          - label: "ğŸš€"
            url: https://springboot.casemanager
            order: 2000

# Spring Boot Admin ç™»å½•è´¦å·å¯†ç 
case-manager:
  admin:
    username: admin
    password: admin
